import { next, rewrite } from "@vercel/functions";

// Generated by scripts/render_issue_html.py. Ids stay in sync with public/issue-pages/.
const ISSUE_IDS = new Set([
  "2026-09-26-87k-rejection",
  "2026-09-23-still-early-shape",
  "2026-09-22-the-87k-door",
  "2026-09-18-the-bid-went-missing",
  "2026-09-17-dont-skip-to-28k",
  "2026-09-11-twenty-five-looked-strong",
  "2026-09-07-crash-is-the-tail",
  "2026-09-06-may-highs-still-live",
  "2026-09-04-eighty-one-probe",
  "2026-09-03-yen-carry-sleeve",
  "2026-09-02-four-year-cycle-on-trial",
  "2026-09-01-crash-stack-on-trial",
  "2026-08-31-zz-price-of-waiting",
  "2026-08-31-two-tapes",
  "2026-08-30-stall-not-a-floor",
  "2026-08-28-zz-bang-clear-map",
  "2026-08-28-z-warsh-social-tape",
  "2026-08-28-y-thirty-eight-floor",
  "2026-08-28-x-bang-scalp-long",
  "2026-08-28-what-voo-owns",
  "2026-08-28-warsh-morning",
  "2026-08-27-september-box",
  "2026-08-27-after-the-prints",
  "2026-08-26-full-bench",
  "2026-08-25-bang-stopped",
  "2026-08-24-second-probe",
  "2026-08-22-the-window"
]);

export const config = {
  matcher: "/issue",
};

export default function middleware(request) {
  const id = new URL(request.url).searchParams.get("id") || "";
  if (!ISSUE_IDS.has(id)) return next();
  const dest = new URL("/issue-pages/" + id, request.url);
  dest.search = "";
  return rewrite(dest);
}
