#!/usr/bin/env python3
"""Write evergreen topic hub pages (public/topics/*.html) from scripts/topics.json.

Each hub explains one recurring theme and links every issue on it in plain HTML, so search
visitors landing on a broad question ("is the four-year cycle still working?") can reach the
archive. Issues are assigned by keyword hits in title, dek and body, plus pinned/include ids,
so new letters join the right hubs when publish_letter.py reruns.
"""

from __future__ import annotations

import html
import json
import re
from datetime import date
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
ISSUES = PUBLIC / "issues"
OUT = PUBLIC / "topics"
CONFIG = Path(__file__).resolve().parent / "topics.json"
INDEX = PUBLIC / "index.html"
SITE = "https://www.paramariboletter.com"
BRAND = "The Paramaribo Letter"
TOPICS_START = "<!-- topics:start (generated by scripts/build_topics.py) -->"
TOPICS_END = "<!-- topics:end -->"
TAG_RE = re.compile(r"<[^>]+>")


def esc(value: str) -> str:
    return html.escape(value or "", quote=True)


def fmt_date(iso: str) -> str:
    try:
        day = date.fromisoformat(iso)
    except ValueError:
        return iso
    return f"{day.strftime('%B')} {day.day}, {day.year}"


def issue_url(issue_id: str) -> str:
    return f"/issue?id={quote(issue_id, safe='')}"


def topic_url(slug: str) -> str:
    return f"/topics/{slug}"


def json_ld(data: dict) -> str:
    text = json.dumps(data, ensure_ascii=False, indent=2).replace("<", "\\u003c")
    return f'<script type="application/ld+json">\n{text}\n  </script>'


def load_topics() -> list[dict]:
    return json.loads(CONFIG.read_text())


def load_issues() -> list[dict]:
    rows = []
    for path in ISSUES.glob("*.json"):
        meta = json.loads(path.read_text())
        body_path = path.with_suffix(".body.html")
        meta["body"] = body_path.read_text() if body_path.exists() else ""
        rows.append(meta)
    rows.sort(key=lambda row: (row.get("date") or "", row.get("id") or ""), reverse=True)
    return rows


def assign(rows: list[dict], topics: list[dict] | None = None) -> dict[str, list[dict]]:
    """Map topic slug -> issues on that topic, newest first."""
    topics = topics if topics is not None else load_topics()
    out: dict[str, list[dict]] = {}
    for topic in topics:
        pattern = re.compile(topic["pattern"], re.I)
        forced = set(topic.get("pinned", [])) | set(topic.get("include", []))
        matched = []
        for row in rows:
            text = " ".join([row.get("title") or "", row.get("dek") or "", TAG_RE.sub(" ", row.get("body") or "")])
            if row["id"] in forced or len(pattern.findall(text)) >= topic.get("min_hits", 1):
                matched.append(row)
        out[topic["slug"]] = matched
    return out


def topics_for_issue(issue_id: str, assigned: dict[str, list[dict]], topics: list[dict]) -> list[dict]:
    return [t for t in topics if any(r["id"] == issue_id for r in assigned.get(t["slug"], []))]


def topic_links_html(topics: list[dict]) -> str:
    """Inline 'Topics:' line for issue pages."""
    if not topics:
        return ""
    links = " · ".join(f'<a href="{esc(topic_url(t["slug"]))}">{esc(t["name"])}</a>' for t in topics)
    return f'<p class="topic-links">Topics: {links}</p>'


def card_html(row: dict) -> str:
    """Same markup as cardHTML() in public/app.js."""
    return f"""
      <a class="feed-card" href="{esc(issue_url(row['id']))}">
        <img src="/{esc((row.get('cover') or 'images/masthead.png').lstrip('/'))}" alt="" loading="lazy" decoding="async">
        <div>
          <div class="feed-kicker">{esc(row.get('kicker') or '')}</div>
          <h3>{esc(row.get('title') or row['id'])}</h3>
          <p>{esc(row.get('dek') or '')}</p>
          <div class="feed-meta">{esc(fmt_date(row.get('date') or ''))} · {esc(row.get('byline') or BRAND)}</div>
        </div>
      </a>"""


def head_html(title: str, description: str, canonical: str, extra_ld: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(description)}" />
  <link rel="canonical" href="{esc(canonical)}" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="{esc(BRAND)}" />
  <meta property="og:title" content="{esc(title)}" />
  <meta property="og:description" content="{esc(description)}" />
  <meta property="og:url" content="{esc(canonical)}" />
  <meta property="og:image" content="{SITE}/images/masthead.png" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{esc(title)}" />
  <meta name="twitter:description" content="{esc(description)}" />
  <meta name="twitter:image" content="{SITE}/images/masthead.png" />
  <link rel="alternate" type="application/rss+xml" title="{esc(BRAND)}" href="{SITE}/feed.xml" />
  {extra_ld}
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="icon" href="/favicon-32.png" type="image/png" sizes="32x32" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
  <link rel="stylesheet" href="/styles.css" />
  <script>
    try {{
      var t = localStorage.getItem("paramaribo-theme");
      document.documentElement.dataset.theme = t === "light" ? "light" : "dark";
    }} catch (e) {{
      document.documentElement.dataset.theme = "dark";
    }}
  </script>
  <script>
    window.va = window.va || function () {{ (window.vaq = window.vaq || []).push(arguments); }};
  </script>
  <script defer src="/_vercel/insights/script.js"></script>
  <script defer src="/clarity.js"></script>
</head>"""


SUBSCRIBE_AND_FOOTER = """    <section class="subscribe-box subscribe-hook" id="new-subscribers" aria-labelledby="sub-title">
      <h2 id="sub-title">Get the next letter by email</h2>
      <p class="subscribe-lede">Each letter writes the levels down before the tape decides, then checks them in the next one. Free, no spam, one click to leave.</p>
      <form class="subscribe-form" data-subscribe-form data-sub-location="topic">
        <label class="sr-only" for="sub-email">Email</label>
        <input id="sub-email" name="email" type="email" required placeholder="you@example.com" autocomplete="email" />
        <input class="hp" name="company" type="text" tabindex="-1" autocomplete="off" aria-hidden="true" />
        <button class="btn btn-primary" type="submit">Email me the next letter</button>
      </form>
      <p class="subscribe-status" data-sub-status aria-live="polite"></p>
      <p class="subscribe-unsub">Already on the list? <a href="/unsubscribe">Unsubscribe</a>. Educational research only.</p>
    </section>
    <footer class="site">
      <div>© The Paramaribo Letter</div>
      <div><a href="/">All letters</a> · <a href="/topics">Topics</a> · <a href="/#new-subscribers">Subscribe</a> · <a href="/agents">Agents</a></div>
    </footer>
  </div>
  <script src="/catalog.js"></script>
  <script src="/subscribe.js"></script>
  <script src="/shell.js"></script>
</body>
</html>
"""


def breadcrumb_ld(items: list[tuple[str, str]]) -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": url} for i, (name, url) in enumerate(items)
        ],
    }


def render_topic(topic: dict, rows: list[dict], topics: list[dict]) -> str:
    slug = topic["slug"]
    canonical = f"{SITE}{topic_url(slug)}"
    by_id = {r["id"]: r for r in rows}
    pinned = [by_id[i] for i in topic.get("pinned", []) if i in by_id]
    collection = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": topic["title"],
        "description": topic["description"],
        "url": canonical,
        "isPartOf": {"@type": "WebSite", "name": BRAND, "url": f"{SITE}/"},
        "dateModified": rows[0].get("date") if rows else "",
        "mainEntity": {
            "@type": "ItemList",
            "numberOfItems": len(rows),
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": i + 1,
                    "url": f"{SITE}/issue?id={quote(r['id'], safe='')}",
                    "name": r.get("title") or r["id"],
                }
                for i, r in enumerate(rows)
            ],
        },
    }
    crumbs = breadcrumb_ld([("Home", f"{SITE}/"), ("Topics", f"{SITE}/topics"), (topic["name"], canonical)])
    ld = json_ld(collection) + "\n  " + json_ld(crumbs)
    intro = "\n".join(f"        <p>{esc(p)}</p>" for p in topic.get("intro", []))
    questions = "\n".join(f"          <li>{esc(q)}</li>" for q in topic.get("questions", []))
    start = "".join(card_html(r) for r in pinned)
    items = "\n".join(
        f'        <li><a href="{esc(issue_url(r["id"]))}">{esc(r.get("title") or r["id"])}</a>'
        f' <span class="more-letters-date">{esc(fmt_date(r.get("date") or ""))}</span>'
        f'<br><span class="topic-item-dek">{esc(r.get("dek") or "")}</span></li>'
        for r in rows
    )
    others = " · ".join(
        f'<a href="{esc(topic_url(t["slug"]))}">{esc(t["name"])}</a>' for t in topics if t["slug"] != slug
    )
    updated = fmt_date(rows[0].get("date") or "") if rows else ""
    return f"""{head_html(f"{topic['title']} · {BRAND}", topic["description"], canonical, ld)}
<body data-nav="topics">
  <div class="portal-stage wrap">
    <article class="topic-page">
      <nav class="topic-crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › <a href="/topics">Topics</a> › {esc(topic["name"])}</nav>
      <h1>{esc(topic["title"])}</h1>
      <p class="lede">{esc(topic["dek"])}</p>
      <div class="meta">{len(rows)} letters · updated {esc(updated)}</div>
      <div class="body topic-intro">
{intro}
      </div>
      <aside class="topic-questions">
        <h2>Questions this page answers</h2>
        <ul>
{questions}
        </ul>
      </aside>
    </article>
    <section class="feed-head"><h2>Start here</h2></section>
    <div class="feed">{start}
    </div>
    <nav class="more-letters" aria-label="Every letter on this topic">
      <h2>Every letter on {esc(topic["name"].lower())}</h2>
      <ul>
{items}
      </ul>
      <p>More topics: {others}</p>
      <p><a href="/">All letters</a> · <a href="/charts">Charts</a> · <a href="/cases">Case studies</a></p>
    </nav>
    <p class="disclaimer">Educational scenario research. Not personalized financial advice. Levels and weights are as written in each dated letter; older issues stay in the archive unchanged.</p>
{SUBSCRIBE_AND_FOOTER}"""


def render_index(topics: list[dict], assigned: dict[str, list[dict]]) -> str:
    canonical = f"{SITE}/topics"
    title = f"Bitcoin and Macro Research by Topic · {BRAND}"
    description = (
        "Browse The Paramaribo Letter by topic: Bitcoin's four-year cycle, crash and bottom scenarios, "
        "ETF flows and leverage, the Fed and the yen, and the support and resistance map."
    )
    crumbs = breadcrumb_ld([("Home", f"{SITE}/"), ("Topics", canonical)])
    cards = "\n".join(
        f"""      <a class="topic-card" href="{esc(topic_url(t['slug']))}">
        <h2>{esc(t['title'])}</h2>
        <p>{esc(t['dek'])}</p>
        <span class="feed-meta">{len(assigned.get(t['slug'], []))} letters</span>
      </a>"""
        for t in topics
    )
    return f"""{head_html(title, description, canonical, json_ld(crumbs))}
<body data-nav="topics">
  <div class="portal-stage wrap">
    <section class="feed-head">
      <h1>Topics</h1>
      <span class="feed-toggle">Evergreen guides to the archive</span>
    </section>
    <p class="cases-intro">Each topic page explains one recurring question in plain language and links every letter that works on it, newest first. Start with the theme you came for.</p>
    <div class="topic-grid">
{cards}
    </div>
{SUBSCRIBE_AND_FOOTER}"""


def write_home_topics(topics: list[dict], assigned: dict[str, list[dict]]) -> None:
    text = INDEX.read_text()
    if TOPICS_START not in text or TOPICS_END not in text:
        print("index.html has no topics markers; skipped homepage topics")
        return
    head, rest = text.split(TOPICS_START, 1)
    _, tail = rest.split(TOPICS_END, 1)
    links = "".join(
        f'\n        <li><a href="{esc(topic_url(t["slug"]))}">{esc(t["name"])}</a></li>'
        for t in topics
    )
    block = f"""
    <section class="home-topics" aria-labelledby="topics-title">
      <h2 id="topics-title">Browse by topic</h2>
      <ul class="topic-chips">{links}
        <li><a href="/topics">All topics</a></li>
      </ul>
    </section>
    """
    INDEX.write_text(f"{head}{TOPICS_START}{block}{TOPICS_END}{tail}")
    print("wrote homepage topics")


def sitemap_entries() -> list[tuple[str, str | None]]:
    """(url, lastmod) pairs for build_feeds.py."""
    topics = load_topics()
    assigned = assign(load_issues(), topics)
    newest = [rows[0].get("date") for rows in assigned.values() if rows]
    entries = [(f"{SITE}/topics", max(newest) if newest else None)]
    for t in topics:
        rows = assigned.get(t["slug"], [])
        entries.append((f"{SITE}{topic_url(t['slug'])}", rows[0].get("date") if rows else None))
    return entries


def main() -> int:
    topics = load_topics()
    rows = load_issues()
    assigned = assign(rows, topics)
    OUT.mkdir(parents=True, exist_ok=True)
    keep = {"index.html"}
    for topic in topics:
        dest = OUT / f"{topic['slug']}.html"
        dest.write_text(render_topic(topic, assigned[topic["slug"]], topics))
        keep.add(dest.name)
        print(f"wrote {dest.relative_to(ROOT)} ({len(assigned[topic['slug']])} letters)")
    (OUT / "index.html").write_text(render_index(topics, assigned))
    print(f"wrote {(OUT / 'index.html').relative_to(ROOT)}")
    for stale in OUT.glob("*.html"):
        if stale.name not in keep:
            stale.unlink()
            print(f"removed {stale.relative_to(ROOT)}")
    write_home_topics(topics, assigned)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
