#!/usr/bin/env python3
"""Write one HTML file per issue so the first response already has the title and social tags.

Vercel middleware rewrites /issue?id=<id> to /issue-pages/<id>. Crawlers that do not run
app.js still see the catalog title, dek, cover, canonical, and Twitter tags.
"""

from __future__ import annotations

import html
import json
from datetime import date
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
ISSUES = PUBLIC / "issues"
OUT = PUBLIC / "issue-pages"
SITE = "https://www.paramariboletter.com"
BRAND = "The Paramaribo Letter"
ID_OK = __import__("re").compile(r"^[a-z0-9][a-z0-9-]{0,120}$")
INDEX = PUBLIC / "index.html"
FEED_START = "<!-- feed:start (generated by scripts/render_issue_html.py) -->"
FEED_END = "<!-- feed:end -->"
RELATED_COUNT = 5


def esc(value: str) -> str:
    return html.escape(value or "", quote=True)


def fmt_date(iso: str) -> str:
    try:
        day = date.fromisoformat(iso)
    except ValueError:
        return iso
    return f"{day.strftime('%B')} {day.day}, {day.year}"


def absolute_cover(cover: str) -> str:
    path = (cover or "").strip() or "images/masthead.png"
    if path.startswith("https://") or path.startswith("http://"):
        return path
    return f"{SITE}/{path.lstrip('/')}"


def issue_url(issue_id: str) -> str:
    return f"/issue?id={quote(issue_id, safe='')}"


def json_ld(data: dict) -> str:
    # Escape "<" so a title can never close the script tag early.
    text = json.dumps(data, ensure_ascii=False, indent=2).replace("<", "\\u003c")
    return f'<script type="application/ld+json">\n{text}\n  </script>'


def article_ld(row: dict, canonical: str, image: str) -> str:
    publisher = {
        "@type": "Organization",
        "name": BRAND,
        "url": f"{SITE}/",
        "logo": {"@type": "ImageObject", "url": f"{SITE}/paramaribo-letter-logo-300.png"},
    }
    data = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": row.get("title") or row["id"],
        "description": row.get("dek") or row.get("title") or "",
        "image": [image],
        "datePublished": row.get("date") or "",
        "dateModified": row.get("date") or "",
        "author": {"@type": "Organization", "name": row.get("byline") or BRAND, "url": f"{SITE}/agents"},
        "publisher": publisher,
        "mainEntityOfPage": {"@type": "WebPage", "@id": canonical},
        "isAccessibleForFree": True,
    }
    return json_ld(data)


def card_html(row: dict) -> str:
    """Same markup as cardHTML() in public/app.js, so the page does not shift when JS runs."""
    byline = row.get("byline") or BRAND
    return f"""
    <a class="feed-card" href="{esc(issue_url(row['id']))}">
      <img src="{esc(row.get('cover') or 'images/masthead.png')}" alt="" loading="lazy" decoding="async">
      <div>
        <div class="feed-kicker">{esc(row.get('kicker') or '')}</div>
        <h2>{esc(row.get('title') or row['id'])}</h2>
        <p>{esc(row.get('dek') or '')}</p>
        <div class="feed-meta">{esc(fmt_date(row.get('date') or ''))} · {esc(byline)}</div>
      </div>
    </a>"""


def related_html(row: dict, rows: list[dict]) -> str:
    """Newer/older links plus recent letters, so every issue links to others in plain HTML."""
    idx = next(i for i, r in enumerate(rows) if r["id"] == row["id"])
    newer = rows[idx - 1] if idx > 0 else None
    older = rows[idx + 1] if idx + 1 < len(rows) else None
    nav = []
    if older:
        nav.append(f'<a rel="prev" href="{esc(issue_url(older["id"]))}">← Previous: {esc(older.get("title") or older["id"])}</a>')
    if newer:
        nav.append(f'<a rel="next" href="{esc(issue_url(newer["id"]))}">Next: {esc(newer.get("title") or newer["id"])} →</a>')
    skip = {row["id"]} | {r["id"] for r in (newer, older) if r}
    recent = [r for r in rows if r["id"] not in skip][:RELATED_COUNT]
    items = "\n".join(
        f'        <li><a href="{esc(issue_url(r["id"]))}">{esc(r.get("title") or r["id"])}</a>'
        f' <span class="more-letters-date">{esc(fmt_date(r.get("date") or ""))}</span></li>'
        for r in recent
    )
    nav_html = "\n".join(f"        {link}" for link in nav)
    return f"""<nav class="more-letters" aria-label="More letters">
      <div class="more-letters-nav">
{nav_html}
      </div>
      <h2>More from the letter</h2>
      <ul>
{items}
      </ul>
      <p><a href="/">All letters</a> · <a href="/charts">Charts</a> · <a href="/cases">Case studies</a></p>
    </nav>"""


def load_issues() -> list[dict]:
    rows = []
    for path in ISSUES.glob("*.json"):
        meta = json.loads(path.read_text())
        issue_id = meta.get("id") or ""
        if not ID_OK.match(issue_id):
            raise SystemExit(f"refusing issue id that is not a safe slug: {issue_id!r}")
        body_path = path.with_suffix(".body.html")
        meta["body"] = body_path.read_text() if body_path.exists() else ""
        rows.append(meta)
    rows.sort(key=lambda row: (row.get("date") or "", row.get("id") or ""), reverse=True)
    return rows


def render_issue(row: dict, rows: list[dict]) -> str:
    issue_id = row["id"]
    title = row.get("title") or issue_id
    dek = row.get("dek") or title
    document_title = f"{title} · {BRAND}"
    canonical = f"{SITE}/issue?id={quote(issue_id, safe='')}"
    image = absolute_cover(row.get("cover") or "")
    cover_src = "/" + (row.get("cover") or "images/masthead.png").strip().lstrip("/")
    kicker = row.get("kicker") or ""
    byline = row.get("byline") or BRAND
    meta_line = f"{fmt_date(row.get('date') or '')} · {byline}"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{esc(document_title)}</title>
  <meta name="description" content="{esc(dek)}" />
  <link rel="canonical" href="{esc(canonical)}" />
  <meta property="og:type" content="article" />
  <meta property="og:site_name" content="{esc(BRAND)}" />
  <meta id="og-title" property="og:title" content="{esc(document_title)}" />
  <meta id="og-desc" property="og:description" content="{esc(dek)}" />
  <meta id="og-image" property="og:image" content="{esc(image)}" />
  <meta id="og-url" property="og:url" content="{esc(canonical)}" />
  <meta property="og:image:alt" content="{esc(title)}" />
  <meta property="article:published_time" content="{esc(row.get('date') or '')}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{esc(document_title)}" />
  <meta name="twitter:description" content="{esc(dek)}" />
  <meta name="twitter:image" content="{esc(image)}" />
  <link rel="alternate" type="application/rss+xml" title="{esc(BRAND)}" href="{SITE}/feed.xml" />
  {article_ld(row, canonical, image)}
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="icon" href="/favicon-32.png" type="image/png" sizes="32x32" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
  <link rel="stylesheet" href="/styles.css" />
  <script>
    try {{
      var t = localStorage.getItem("paramaribo-theme");
      document.documentElement.dataset.theme = t === "light" ? "light" : "dark";
    }} catch (e) {{
      document.documentElement.dataset.theme = "dark";
    }}
  </script>
  <script>
    window.va = window.va || function () {{ (window.vaq = window.vaq || []).push(arguments); }};
  </script>
  <script defer src="/_vercel/insights/script.js"></script>
</head>
<body data-nav="feed">
  <div class="portal-stage wrap">
    <article class="issue-page">
      <div class="kicker" id="kicker">{esc(kicker)}</div>
      <h1 id="title">{esc(title)}</h1>
      <p class="lede" id="dek">{esc(dek)}</p>
      <div class="meta" id="meta">{esc(meta_line)}</div>
      <img class="cover" id="cover" src="{esc(cover_src)}" alt="{esc(title)}" />
      <div class="body" id="body">
{row.get("body") or ""}
      </div>
      <p class="disclaimer">Educational scenario research. Not personalized financial advice. No execution, no position sizing, no leverage recommendation. Older issues remain in the archive and are not removed when a new letter is posted. <a href="/agents">Read who the agents are</a>.</p>
    </article>
    {related_html(row, rows)}
    <section class="subscribe-box" id="new-subscribers" aria-labelledby="sub-title">
      <h2 id="sub-title">Subscribe</h2>
      <p class="subscribe-lede">Email when the next letter posts. Educational research only.</p>
      <form class="subscribe-form" data-subscribe-form>
        <label class="sr-only" for="sub-email">Email</label>
        <input id="sub-email" name="email" type="email" required placeholder="you@example.com" autocomplete="email" />
        <input class="hp" name="company" type="text" tabindex="-1" autocomplete="off" aria-hidden="true" />
        <button class="btn btn-primary" type="submit">Subscribe</button>
      </form>
      <p class="subscribe-status" data-sub-status aria-live="polite"></p>
      <p class="subscribe-unsub">Already on the list? <a href="/unsubscribe">Unsubscribe</a>.</p>
    </section>
    <footer class="site">
      <div>© The Paramaribo Letter</div>
      <div><a href="/#new-subscribers">Subscribe</a> · <a href="/unsubscribe">Unsubscribe</a> · <a href="/agents">Agents</a></div>
    </footer>
  </div>
  <script src="/catalog.js"></script>
  <script src="/app.js"></script>
  <script src="/subscribe.js"></script>
  <script src="/shell.js"></script>
  <script>Letter.renderIssue();</script>
</body>
</html>
"""


def write_middleware(ids: list[str]) -> None:
    listed = ",\n".join(f"  {json.dumps(issue_id)}" for issue_id in ids)
    text = f"""import {{ next, rewrite }} from "@vercel/functions";

// Generated by scripts/render_issue_html.py. Ids stay in sync with public/issue-pages/.
const ISSUE_IDS = new Set([
{listed}
]);

export const config = {{
  matcher: "/issue",
}};

export default function middleware(request) {{
  const id = new URL(request.url).searchParams.get("id") || "";
  if (!ISSUE_IDS.has(id)) return next();
  const dest = new URL("/issue-pages/" + id, request.url);
  dest.search = "";
  return rewrite(dest);
}}
"""
    (ROOT / "middleware.js").write_text(text)


def write_index_feed(rows: list[dict]) -> None:
    """Put the letter list in index.html so crawlers see links to every issue without JS."""
    text = INDEX.read_text()
    if FEED_START not in text or FEED_END not in text:
        print("index.html has no feed markers; skipped homepage feed")
        return
    head, rest = text.split(FEED_START, 1)
    _, tail = rest.split(FEED_END, 1)
    cards = "".join(card_html(row) for row in rows)
    INDEX.write_text(f"{head}{FEED_START}{cards}\n    {FEED_END}{tail}")
    print(f"wrote homepage feed ({len(rows)} letters)")


def render_issue_pages() -> list[dict]:
    rows = load_issues()
    OUT.mkdir(parents=True, exist_ok=True)
    keep = set()
    for row in rows:
        issue_id = row["id"]
        dest = OUT / f"{issue_id}.html"
        dest.write_text(render_issue(row, rows))
        keep.add(dest.name)
        print(f"wrote {dest.relative_to(ROOT)}")
    for stale in OUT.glob("*.html"):
        if stale.name not in keep:
            stale.unlink()
            print(f"removed {stale.relative_to(ROOT)}")
    ids = [row["id"] for row in rows]
    write_middleware(ids)
    write_index_feed(rows)
    print(f"wrote middleware.js ({len(ids)} issue ids)")
    return rows


def main() -> int:
    render_issue_pages()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
